### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by parisgianluca** [jsnomad/koa-restful-boilerplate#2]
Hello, I cloned repository, installed dependencies, but, when running `npm start,` i get:

```
\node_modules\koa-bodyparser\index.js:72
  return async function bodyParser(ctx, next) {
               ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\gianluca.paris\Desktop\a\together\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by guAnsunyata** [comment]
Async functions are not supported by Node versions older than version 7.6.
Please check your node.js version.
